// resources/lesson-7/aem-guides-wknd-events/react-app/src/components/promo/Promo.js

import React, {Component} from 'react';
import {MapTo} from '@adobe/cq-react-editable-components';
import { Button } from '../button/Button';
import { Image } from '../image/Image';
import "./Promo.scss";

/**
 * Promo Edit Config
 * 
 * @type EditConfig
 */
const PromoEditConfig = {

    emptyLabel: 'Promo',

    isEmpty: function(props) {
        return !props || !props.title;
    }
};

/**
 * 
 * Promo React component
 */
export default class Promo extends Component {

    get title() {
        if(this.props.title) {
            return this.props.title;
        }
        return null;
    }

    get description() {
        if(this.props.description) {
            return this.props.description;
        }
        return null;
    }

    get actionLinks() {

        if(this.props.actionItems) {
            return (<div className="Promo-actions">
                {
                    this.props.actionItems.map((actionItem, index) => {
                        return <Button key={index} url={actionItem.url}>{actionItem.title}</Button>
                       })
                }
                </div>);
        }

        return null;
    }

    get image() {
        if(this.props.image) {
            
            return <Image {...this.props.image} alt={this.title} />;
        }

        return null;
    }

    get cssClass() {
        if(this.props.style) {
            return "Promo " + this.props.style;
        }
        return "Promo";
    }

    render() {
        if(!PromoEditConfig.isEmpty(this.props)) {
            return (<div className={this.cssClass}>
                <div className="Promo-image ">
                    {this.image}
                </div>
                <div className="Promo-content">
                    <span className="Promo-sponsor">Sponsored</span>
                    <h3 className="Promo-title">{this.title}</h3>
                    <h6 className="Promo-offer">{this.props.offerText}</h6>
                    <div className="Promo-description" dangerouslySetInnerHTML={{__html:  this.description}}/>
                    {this.actionLinks}
                </div>
            </div>);
        }
        return null;
    }
}

MapTo('wknd-events/components/content/promo')(Promo, PromoEditConfig);

// resources/lesson-3/aem-guides-wknd-events/angular-app/src/app/components/promo/promo.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {MapTo} from '@adobe/cq-angular-editable-components';
/**
 * Promo Edit Config
 *
 * @type EditConfig
 */
const PromoEditConfig = {

  emptyLabel: 'Promo',

  isEmpty: function(componentData) {
    return !componentData || !componentData.title;
  }
};

@Component({
  selector: 'app-promo',
  templateUrl: './promo.component.html'
})
export class PromoComponent implements OnInit {
  @Input() title: string;
  @Input() description: string;
  @Input() image: any;
  @Input() actionItems: any;

  constructor() { }

  get hasTitle() {
    return this.title && this.title.trim().length > 0;
  }

  ngOnInit() {
  }

}
<div *ngIf="hasTitle" class="Promo">
  <div class="Promo-image ">
    <img [alt]="title" [src]="image.src" />
  </div>
  <div class="Promo-content">
    <span class="Promo-sponsor">Sponsored</span>
    <h3 class="Promo-title">{{title}}</h3>
    <div class="Promo-description" [innerHTML]=description></div>
    <div *ngIf="actionItems" className="Promo-actions">
      <app-button *ngFor="let actionItem of actionItems" [url]="actionItem.url" [title]="actionItem.title"></app-button>
    </div>
  </div>
</div>
