// resources/lesson-3/aem-guides-wknd-events/react-app/src/components/button/Button.js
import React, { Component } from 'react';
import {Link} from "react-router-dom";
import "./Button.scss";

const sizeClasses = {
    "M" : "Button--M",
    "L" : "Button--L"
}

const variantClasses = {
    "primary": "Button--primary",
    "secondary": "Button--secondary"
}

export class Button extends Component {
    constructor(props) {
        super(props);
        this.state = {
            size: this.props.size || "L",
            variant: this.props.variant || "primary"
        }
    }
    
    get classes() {
        return `Button ${sizeClasses[this.state.size]} ${variantClasses[this.state.variant]}`;
    }

    render() {
        return (<Link className={ this.classes } to={this.props.url}>{ this.props.children }</Link>);
    }
}

// resources/lesson-3/aem-guides-wknd-events/angular-app/src/app/components/button/button.component.ts
import {Component, Input, OnInit} from '@angular/core';

const sizeClasses = {
  "M" : "Button--M",
  "L" : "Button--L"
}

const variantClasses = {
  "primary": "Button--primary",
  "secondary": "Button--secondary"
}

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss']
})

export class ButtonComponent implements OnInit {

  @Input() size: string;
  @Input() variant: string;
  @Input() url: string;
  @Input() title: string;

  constructor() { }

  get classes() {
    return `Button ` + sizeClasses[this.size] + ` ` + variantClasses[this.variant];
  }

  ngOnInit() {
    this.size = this.size || "L";
    this.variant = this.variant || "primary";
  }

}

<a [class]="classes" [routerLink]="url">{{title}}</a>
