// resources/lesson-3/aem-guides-wknd-events/angular-app/src/app/components/header/header.component.ts
import { ActivatedRoute } from '@angular/router';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  public home: boolean;

  constructor(private route: ActivatedRoute) {
      this.home = route.snapshot.data.home;
  }

  ngOnInit() {}

}

<header class="header">
  <div class="wrapper">
    <a class="link" routerLink={{homePath}}>
      <h1 class="title">WKND<span class="title--inverse">_</span></h1>
    </a>
    <div class="header-tools" *ngIf=!home>
      <a class="header-action" routerLink="{{homePath}}">
        Back
      </a>
    </div>
  </div>
</header>

// resources/lesson-3/aem-guides-wknd-events/react-app/src/components/header/Header.js
import React, { Component } from 'react';
import { Link } from "react-router-dom";
import { withRouter } from 'react-router';
import './Header.scss';

class Header extends Component {

    get homeLink() {
        let currLocation;
        currLocation = this.props.location.pathname;
        currLocation = currLocation.substr(0, currLocation.length - 5);

        if (this.props.navigationRoot && currLocation !== this.props.navigationRoot) {
            return (<Link className="Header-action" to={this.props.navigationRoot + ".html"}>
                Back
            </Link>);
        }
        return null;
    }

    render() {
        return (
            <header className="Header">
                <div className="Header-wrapper">
                    <h1 className="Header-title">WKND<span className="Header-title--inverse">_</span></h1>
                    <div className="Header-tools">
                        { this.homeLink }
                   </div>
                </div>
            </header>
        );
    }
}

export default withRouter(Header);
